### ISSUE TITLE
dftTest appears to be broken

### ISSUE THREAD

**Issue by DanielSWolf** [runk/randomness#427]
I'm passing an array of 80,000 bits to `dftTest`. All other tests work fine, but this one throws the following error:

```text
/Users/wolf/dev/crossmip/node_modules/fft-js/src/complex.js:24
    return [(a[0] * b[0] - a[1] * b[1]), 
                     ^

TypeError: Cannot read properties of undefined (reading '0')
    at Object.complexMultiply [as multiply] (/Users/wolf/dev/crossmip/node_modules/fft-js/src/complex.js:24:22)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:55:23)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
    at fft (/Users/wolf/dev/crossmip/node_modules/fft-js/src/fft.js:46:19)
```

**Comment by runk** [comment]
Hmm... This appears to be a problem in fft-js module. I'd recommend to raise an issue there, ideally with reproducible example.
